# Generated by Django 5.1.4 on 2025-01-21 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0002_alter_movies_image_mylist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="mylist",
            new_name="userlist",
        ),
    ]
